<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Auth;
use Eloquent;
use App\Http\Controllers\LearnedWordController;

class LessonWord extends Model
{
    protected $table = 'lesson_word';
    protected $fillable = ['lesson_id', 'word_id', 'word_answered_id'];

    public function word()
    {
        return $this->belongsTo(Word::class, 'word_id');
    }

    public function wordAnswered()
    {
        return $this->belongsTo(Word::class, 'word_answered_id');
    }

    public function lesson()
    {
        return $this->belongsTo(Lesson::class);
    }

    public function scopeGetLessonWords($query, $lessonId)
    {
        return $query->with(['word', 'wordAnswered', 'word.category'])
            ->where('lesson_id', $lessonId);
    }

    public function generateLessonWords($request, $user)
    {
        // Fetch the ids of learned words to be used in querying the words that have not been learned yet
        $lessonWords = Category::findOrFail($request->category_id)
            ->words()
            ->userUnlearnedWords($user)
            ->orderBy(\DB::raw('RAND()'))
            ->take(5)
            ->get();

        $lessonWordsToInsert = [];
        foreach ($lessonWords as $lessonWord) {
            $lessonWordsToInsert[] = [
                'lesson_id' => $request->lesson_id,
                'word_id' => $lessonWord->id,
                'word_answered_id' => null
            ];
        }

        try {
            Eloquent::insert($lessonWordsToInsert);
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

    public function setAnswer($request)
    {
        $this->update([
            'word_answered_id' => $request->input('word_answer_id')
        ]);

        // Now check if the words match
        if($this->word_id == $this->word_answered_id) {
            $request->request->add(['word_id' => $this->word_id]);
            $learnedWord = new LearnedWordController;
            $learnedWord->store($request); // Add word id to Learned Words
        }
    }

    /*
     * Returns the most recent lesson_id generated by the current user
     */
    public function getLastLessonId($id)
    {
        return Lesson::where('user_id', '=', $id)->latest()->first()->id;
    }
}
